try {
  // Lo que deseamos que se ejecute
  console.log("Inicio del try");
} catch (error) {
  //Ejecutamos el error ocurrido en el try
  console.log("Ocurri√≥ un error");
  console.log(error);
}
